// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Discs.Models;

public partial class DiscGolfDBContext : DbContext
{
    public DiscGolfDBContext(DbContextOptions<DiscGolfDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Disc> Discs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Disc>(entity =>
        {
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Plastic).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}