// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Discs.Models;

public class Disc
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Plastic { get; set; }

    public double Speed { get; set; }

    public int Glide { get; set; }

    public double Turn { get; set; }

    public double Fade { get; set; }

    public Manufacturer Manufacturer { get; set; }

    public DiscType DiscType { get; set; }

    [JsonIgnore]
    [IgnoreDataMember]
    [NotMapped]
    public int TimesUsed { get; set; }

    public static Disc Create(string name, string plastic, double speed, int glide, double turn, double fade)
    {
        return new Disc { Name = name, 
            Plastic = plastic, 
            Speed = speed, 
            Glide = glide, 
            Turn = turn, 
            Fade = fade,
            Manufacturer = Manufacturer.Innova,
            DiscType = DiscType.Putter
        };
    }


}

public enum Manufacturer
{
    Innova = 0,
    Discmania = 1,
    Discraft = 2,
    Prodigy = 3,
    DynamicDiscs = 4,
    Latitude64 = 5,
    WestsideDiscs = 6,
    MVP = 7,
    Axiom = 8,
    Streamline = 9,
    Kastaplast = 10
}

public enum DiscType
{
    Putter = 0,
    MidRange = 1,
    FairwayDriver = 2,
    DistanceDriver = 3
}